### Author : Riasad Alvi
### Date : 28 Feb 2025

### **What is Embedding?**  
An embedding is a way to represent words as dense numerical vectors instead of simple integers. It captures word meaning and relationships in a continuous vector space.  

### **How is it Used in RNN?**  
1. Each word (integer) is mapped to a fixed-size vector (e.g., 100D).  
2. These vectors are learned during training or pre-trained (e.g., Word2Vec, GloVe).  
3. The embedding layer feeds these vectors into the RNN, making learning more effective.  

### **Example (Conceptual)**  
- Words: `["dog", "cat", "apple"]`  
- Integer encoding: `[1, 2, 3]`  
- Embedding: `1 → [0.2, -0.3, 0.5]`, `2 → [0.1, 0.4, -0.2]`, `3 → [-0.5, 0.6, 0.8]`  
- These vectors are input to the RNN instead of raw integers.

Embedding performs better than integer encoding because it captures semantic relationships between words. Integer encoding only represents words as distinct IDs, while embeddings create vectors where similar words have similar values, helping the model understand word meanings and context more effectively. This improves performance, especially for tasks like language modeling or sentiment analysis.

In [1]:
# Import necessary modules
import numpy as np
import tensorflow as tf #added import
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten

# input text :
docs = [
    'make america bankrupt again',
    'fake news! fake news!',
    'biggest hands in history, believe me',
    'i know words, i have the best words',
    'covfefe was a message from the future',
    'nobody respects women more than me',
    'i am, like, a really smart person',
    'windmills cause cancer, folks',
    'china china china!',
    'mexico will pay for the wall... eventually'
]


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer  # Imports the Tokenizer class from Keras

tokenizer = Tokenizer()  # Initializes a Tokenizer instance
# This tokenizer will be used to convert text into sequences of integers, where each integer represents a word in the dataset.
# The tokenizer will learn a vocabulary based on the input texts when 'fit_on_texts' is called.


In [12]:
tokenizer.fit_on_texts(docs)
# This method updates the internal vocabulary of the Tokenizer based on the input texts in 'docs'.
# It processes the text and assigns a unique integer index to each word in the dataset.
# The tokenizer learns the vocabulary and prepares to convert the text into sequences of integers.

# Example (conceptual):
# Input:
# docs = ['make america great again', 'fake news', 'biggest hands in history']
# The tokenizer creates a dictionary (word_index) mapping each word to an index, e.g.:
# {'make': 1, 'america': 2, 'great': 3, 'again': 4, 'fake': 5, 'news': 6, 'biggest': 7, 'hands': 8, 'in': 9, 'history': 10}


In [4]:
len(tokenizer.word_index)  # Returns the number of unique words in the tokenizer's vocabulary

# 'word_index' is a dictionary mapping each word in the dataset to a unique integer index.


45

In [5]:
sequences = tokenizer.texts_to_sequences(docs)  # Converts the list of documents into sequences of integers
sequences  # Prints the sequences of integers
# This transforms each document in the `docs` list into a sequence of integers, where each integer represents a word's index in the tokenizer's vocabulary.
# Example output (actual numbers may vary depending on the word indexing):
# [[1, 2, 3, 4], [5, 6, 5, 6], [7, 8, 9, 10, 11], ...]

# Each integer corresponds to a word in the vocabulary learned by the tokenizer.
# The output is a list of lists, where each sublist corresponds to a tokenized document.


[[9, 10, 11, 12],
 [4, 5, 4, 5],
 [13, 14, 15, 16, 17, 6],
 [1, 18, 7, 1, 19, 2, 20, 7],
 [21, 22, 8, 23, 24, 2, 25],
 [26, 27, 28, 29, 30, 6],
 [1, 31, 32, 8, 33, 34, 35],
 [36, 37, 38, 39],
 [3, 3, 3],
 [40, 41, 42, 43, 2, 44, 45]]

In [11]:
from keras.utils import pad_sequences  # Imports pad_sequences function from Keras

sequences = pad_sequences(sequences, padding='post')  # Pads the sequences to ensure uniform length

# 'padding="post"' means that padding (0s) will be added at the end of each sequence.
# This ensures that all sequences in `sequences` have the same length (the longest sequence will define the length).
# Sequences shorter than the maximum length will be padded with 0 at the end.

# Example(conceptual):
# Before padding:
# [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
#
# After padding:
# [[1, 2, 3, 0],
#  [4, 5, 0, 0],
#  [6, 7, 8, 9]]

In [10]:
model = Sequential()  # Initializes a sequential model

model.add(Embedding(45, output_dim=2))
# Adds an Embedding layer with the following parameters:
# - 17: Size of the vocabulary (number of unique words in the dataset)
# - output_dim=2: Each word will be represented by a 2-dimensional vector

model.summary()
# Displays a summary of the model architecture, including the shape of the input/output, number of parameters, and layer details.


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.compile('adam', 'accuracy')
# Compiles the model with the 'adam' optimizer and 'accuracy' as the evaluation metric
# - 'adam' is an adaptive learning rate optimization algorithm
# - 'accuracy' is used as the metric to track the percentage of correct predictions during training

In [9]:
pred = model.predict(sequences)  # Uses the trained model to make predictions on the input sequences

# This returns the predicted output for each sequence in `sequences`.
# The model's output depends on the final layer and task, e.g., for binary classification, the output would be probabilities between 0 and 1.

print(pred)  # Prints the predictions made by the model for each input sequence


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step
[[[-0.00045571  0.02793235]
  [-0.01355758  0.04741564]
  [ 0.04061892  0.01928223]
  [ 0.03049776  0.03492546]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]]

 [[ 0.04809031 -0.02700439]
  [-0.00323854  0.00098864]
  [ 0.04809031 -0.02700439]
  [-0.00323854  0.00098864]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]]

 [[-0.03057381  0.02267602]
  [ 0.03931833 -0.04393272]
  [-0.02348703  0.01900654]
  [-0.0450286   0.02754754]
  [-0.0450286   0.02754754]
  [-0.00985296 -0.04749462]
  [-0.03774194  0.04672808]
  [-0.03774194  0.04672808]]

 [[-0.00530661  0.01264243]
  [-0.0450286   0.02754754]
  [ 0.00298708 -0.01658328]
  [-0.00530661  0.01264243]
  [-0.0450286   0.02754754]
  [ 0.02807382  0.02487714]
  [-0.0450286   0.02754754]
  [ 0.00298708 -0.01658328]]

 [[-0.0450286   0.02754754]
  [-0.0450286   0.02754754]
  [-

In [ ]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model = Sequential()  # Initializes a sequential model

model.add(Embedding(10000, 2, input_length=50))
# Adds an Embedding layer with:
# - 10000: The size of the vocabulary (number of unique words)
# - 2: The output dimension of the embeddings (each word will be represented by a 2-dimensional vector)
# - input_length=50: The input sequences have a length of 50 (i.e., each sequence contains 50 words)

model.add(SimpleRNN(32, return_sequences=False))
# Adds a SimpleRNN layer with 32 units
# 'return_sequences=False' means the RNN layer will only return the last output of the sequence

model.add(Dense(1, activation='sigmoid'))
# Adds a Dense layer with 1 neuron and a sigmoid activation function
# This is used for binary classification (output between 0 and 1)

model.summary()
# Displays a summary of the model architecture, including the output shapes of each layer and the number of parameters.


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# Compiles the model with the following:
# - 'adam' as the optimizer (an adaptive learning rate optimization algorithm)
# - 'binary_crossentropy' as the loss function (used for binary classification tasks)
# - 'acc' (accuracy) as the metric to evaluate the model during training

history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))
# Trains the model with the following parameters:
# - X_train, y_train: Training data (inputs and labels)
# - epochs=5: The model will go through the entire training dataset 5 times
# - validation_data=(X_test, y_test): Evaluates the model on the test data after each epoch to track performance on unseen data
# - 'history' stores the training details like loss and accuracy for each epoch, which can be used for analysis later.


Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - acc: 0.5707 - loss: 0.6556 - val_acc: 0.7787 - val_loss: 0.4775
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8214 - loss: 0.4034 - val_acc: 0.8074 - val_loss: 0.4261
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.8591 - loss: 0.3411 - val_acc: 0.7994 - val_loss: 0.4480
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8661 - loss: 0.3257 - val_acc: 0.7938 - val_loss: 0.4574
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - acc: 0.8787 - loss: 0.3050 - val_acc: 0.7844 - val_loss: 0.4912
